version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - 3009:3009
    env_file: ./api-gateway/.env
    depends_on:
      - redis
      - rabbimq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbimq:5672

  identity-service:
    build: ./identity-service
    ports:
      - 3010:3010
    env_file: ./identity-service/.env
    depends_on:
      - redis
      - rabbimq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbimq:5672

  post-service:
    build: ./post-service
    ports:
      - 3008:3008
    env_file: ./post-service/.env
    depends_on:
      - redis
      - rabbimq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbimq:5672

  media-service:
    build: ./media-service
    ports:
      - 3007:3007
    env_file: ./media-service/.env
    depends_on:
      - redis
      - rabbimq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbimq:5672

  search-service:
    build: ./search-service
    ports:
      - 3006:3006
    env_file: ./search-service/.env
    depends_on:
      - redis
      - rabbimq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbimq:5672

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  rabbimq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnistics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
